name: base-image-build

on:
  push: 
    paths: dev-sec-ops/base-images/


jobs:
  build-base-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build base image
        run: docker build -t ${{secrets.DOCKER_REGISTRY_USER}}/license-finder:latest -f dev-sec-ops/base-images/license-finder.dockerfile .
      
      - name: Login into Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Docker push
        run: docker push ${{secrets.DOCKER_REGISTRY_USER}}/license-finder:latest
