name: Build and Push directory-service Image

on:
  push:
    paths:
      - hospital-management/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Perform Google formatter check
        run: |
          cd hospital-management/directory-service
          mvn com.spotify.fmt:fmt-maven-plugin:check

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: --path=hospital-management/directory-service

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: |
          cd hospital-management/directory-service
          mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker image
        run: |
          cd hospital-management/directory-service
          mvn clean install
          docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Image for directory-service
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest
